<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>技术 on ZCappuccino</title>
        <link>https://example.com/categories/%E6%8A%80%E6%9C%AF/</link>
        <description>Recent content in 技术 on ZCappuccino</description>
        <generator>Hugo -- gohugo.io</generator>
        <language>zh-cn</language>
        <copyright>ZCappuccino</copyright>
        <lastBuildDate>Wed, 25 Dec 2024 21:35:05 +0800</lastBuildDate><atom:link href="https://example.com/categories/%E6%8A%80%E6%9C%AF/index.xml" rel="self" type="application/rss+xml" /><item>
        <title>报错解决-git报错</title>
        <link>https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/</link>
        <pubDate>Wed, 25 Dec 2024 21:35:05 +0800</pubDate>
        
        <guid>https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/</guid>
        <description>&lt;img src="https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/VCG211427864656.jpg" alt="Featured image of post 报错解决-git报错" /&gt;&lt;h2 id=&#34;解决-git-报错-fatal-unable-to-access-httpsgithubcomgit-recv-failure-connection-was-reset&#34;&gt;解决 git 报错 &amp;ldquo;fatal: unable to access ‘https://github.com/&amp;hellip;/.git‘: Recv failure Connection was reset&amp;rdquo;
&lt;/h2&gt;&lt;p&gt;在使用git进行代码管理的过程中，经常会遇到各种各样的问题，其中之一就是在执行git clone时出现 “fatal: unable to access ‘https://github.com/…/.git’: Recv failure Connection was reset” 的报错。这个问题通常是由网络连接问题或代理设置不正确导致的。可以通过设置系统代理的方式解决&lt;br&gt;
具体解决方法如下：&lt;br&gt;&lt;/p&gt;
&lt;h3 id=&#34;打开设置搜索代理设置并点击编辑&#34;&gt;打开设置，搜索代理设置，并点击编辑
&lt;/h3&gt;&lt;p&gt;&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug1.png&#34;
	width=&#34;1447&#34;
	height=&#34;1059&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug1_hu16921911053739716330.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug1_hu11074041846380402878.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;136&#34;
		data-flex-basis=&#34;327px&#34;
	
&gt;&lt;/p&gt;
&lt;h3 id=&#34;在代理服务器中将端口设置为7890&#34;&gt;在代理服务器中，将端口设置为7890
&lt;/h3&gt;&lt;p&gt;7890这个端口通常是默认的，无需修改，并且这个端口不会影响正常上网，可以放心设置
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug2.png&#34;
	width=&#34;1077&#34;
	height=&#34;951&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug2_hu14762356748317864424.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3-git%E6%8A%A5%E9%94%99/gitbug2_hu10254093743468146564.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;113&#34;
		data-flex-basis=&#34;271px&#34;
	
&gt;&lt;/p&gt;
&lt;h3 id=&#34;在终端输入命令设置git使用本地代理&#34;&gt;在终端输入命令，设置git使用本地代理
&lt;/h3&gt;&lt;p&gt;输入如下命令设置：&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-fallback&#34; data-lang=&#34;fallback&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;git config --global http.proxy http://127.0.0.1:7890
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;h3 id=&#34;设置完成后可以通过以下命令检验是否设置成功&#34;&gt;设置完成后，可以通过以下命令检验是否设置成功
&lt;/h3&gt;&lt;p&gt;输入如下命令检验：&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-fallback&#34; data-lang=&#34;fallback&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;git config --global -l
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;p&gt;后面即可git clone成功~&lt;/p&gt;
</description>
        </item>
        <item>
        <title>报错解决记录-算法篇</title>
        <link>https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/</link>
        <pubDate>Fri, 29 Mar 2024 20:55:11 +0800</pubDate>
        
        <guid>https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/</guid>
        <description>&lt;img src="https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/VCG211384587309.jpg" alt="Featured image of post 报错解决记录-算法篇" /&gt;&lt;h2 id=&#34;报错以及对应解决方法&#34;&gt;报错以及对应解决方法
&lt;/h2&gt;&lt;ol&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;StopIteration: Caught StopIteration in replica 0 on device 0.&lt;/b&gt;&lt;br&gt;
原因：使用预训练模型时，原预训练是多卡训练调用时使用单卡，出现问题&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;OSError: We couldn&amp;rsquo;t connect to &amp;lsquo;&lt;a class=&#34;link&#34; href=&#34;https://huggingface.co&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;https://huggingface.co&lt;/a&gt;&amp;rsquo; to load this file, couldn&amp;rsquo;t find it in the cached files and it looks like bert-base-cased is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at &amp;lsquo;&lt;a class=&#34;link&#34; href=&#34;https://huggingface.co/docs/transformers/installation#offline-mode%27&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;https://huggingface.co/docs/transformers/installation#offline-mode&#39;&lt;/a&gt;.&lt;/b&gt;&lt;br&gt;
出现这个问题即无法使用huggingface在线下载预训练BERT&lt;br&gt;
解决：可以将预训练BERT down下来，进行离线加载和使用&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at &lt;a class=&#34;link&#34; href=&#34;https://pytorch.org/get-started/locally/&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;https://pytorch.org/get-started/locally/&lt;/a&gt;
RuntimeError: CUDA error: no kernel image is available for execution on the device&lt;/b&gt;&lt;br&gt;
出现这个问题表示目前安装的torch和cuda的版本与目前GPU不匹配（即版本问题）&lt;br&gt;
解决：重新安装合适的版本：cuda11.1 torch1.8.1&lt;br&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/43.png&#34;
	width=&#34;1046&#34;
	height=&#34;324&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/43_hu13359233568921354043.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/43_hu7125457594470480892.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;322&#34;
		data-flex-basis=&#34;774px&#34;
	
&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt; Anaconda导入导出环境：&lt;/b&gt;&lt;br&gt;
（1）导出：conda env export &amp;gt; E:\Learning\FormulaRecognition\environment.yaml &lt;br&gt;
（2）导入：conda env create -f environment.yaml&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;将代码中.git文件夹删除以后，报错日志“Invalid VCS root mapping: The directory E:\Learning\FormulaRecognition is registered as a Git root, but no Git repositories were found there.”&lt;/b&gt;&lt;br&gt;
解决：（如下图所示）&lt;br&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/44.png&#34;
	width=&#34;1491&#34;
	height=&#34;516&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/44_hu5113100258302824193.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/44_hu4714093632219136283.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;288&#34;
		data-flex-basis=&#34;693px&#34;
	
&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;ImportError: cannot import name &amp;lsquo;OrderedDict&amp;rsquo; from &amp;rsquo;typing&amp;rsquo; (D:\Anaconda\Anaconda3\envs\latexocr\lib\typing.py)&lt;/b&gt;&lt;br&gt;
已解决：&lt;br&gt;
（1） pip install typing_extensions&lt;br&gt;
（2） 修改上文提及的maxvit.py文件，不从typing中导入OrderedDict模块，而是从typing_extensions中导入，即可解决问题。
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/45.png&#34;
	width=&#34;1081&#34;
	height=&#34;79&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/45_hu15711310976060161289.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/45_hu1010055874891875407.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;1368&#34;
		data-flex-basis=&#34;3284px&#34;
	
&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the &amp;lsquo;ssl&amp;rsquo; module is compiled with &amp;lsquo;OpenSSL 1.1.0h 27 Mar 2018&amp;rsquo;.&lt;/b&gt;&lt;br&gt;
已解决：&lt;br&gt;
如果不升级OpenSSL，可以通过降低urlib3的版本来解决冲突。使用以下命令来降低urlib3的版本：&lt;br&gt;&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-fallback&#34; data-lang=&#34;fallback&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;pip install urllib3==1.25.11
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;WARNING: There was an error checking the latest version of pip.&lt;/b&gt;&lt;br&gt;
已解决：&lt;br&gt;
如果不升级OpenSSL，可以通过降低urlib3的版本来解决冲突。使用以下命令来降低urlib3的版本：&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-fallback&#34; data-lang=&#34;fallback&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;pip install urllib3==1.25.11
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;出现如图所示的情况&lt;/b&gt;&lt;br&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/46.png&#34;
	width=&#34;668&#34;
	height=&#34;170&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/46_hu2327144528226602913.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/46_hu3020816145027792792.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;392&#34;
		data-flex-basis=&#34;943px&#34;
	
&gt;
&lt;br&gt;
已解决：关闭VPN，连接稳定WiFi即可解决&lt;br&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;pyinstaller打包：最常见的是运行打包软件以后出现找不到模块的情况(具体如图)：&lt;/b&gt;&lt;br&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/47.png&#34;
	width=&#34;549&#34;
	height=&#34;63&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/47_hu3222417135559693791.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/47_hu2661014681369535736.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;871&#34;
		data-flex-basis=&#34;2091px&#34;
	
&gt;
&lt;br&gt;
解决方法：&lt;br&gt;
在需要打包的py文件中加上import charset_normalizer，然后把环境(比如D:\Anaconda\Anaconda3\envs\latexocr\Lib\site-packages)中的charset_normalizer文件夹放到dist文件下，并把环境中带有.dist-info的文件夹放到dist下（如下图所示）&lt;br&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/48.png&#34;
	width=&#34;1018&#34;
	height=&#34;132&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/48_hu16546540551370176459.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/48_hu754881520731088957.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;771&#34;
		data-flex-basis=&#34;1850px&#34;
	
&gt;
&lt;img src=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/49.png&#34;
	width=&#34;956&#34;
	height=&#34;402&#34;
	srcset=&#34;https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/49_hu5445644909604187520.png 480w, https://example.com/p/%E6%8A%A5%E9%94%99%E8%A7%A3%E5%86%B3%E8%AE%B0%E5%BD%95-%E7%AE%97%E6%B3%95%E7%AF%87/49_hu11473364930391772539.png 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;237&#34;
		data-flex-basis=&#34;570px&#34;
	
&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;数据问题1：UnicodeDecodeError: &amp;lsquo;gbk&amp;rsquo; codec can&amp;rsquo;t decode byte 0x93 in position 2980: illegal multibyte sequence&lt;/b&gt;&lt;br&gt;
已解决：增加encoding=&amp;lsquo;utf-8&amp;rsquo;&lt;br&gt;
代码示例：&lt;br&gt;&lt;/p&gt;
&lt;div class=&#34;highlight&#34;&gt;&lt;div class=&#34;chroma&#34;&gt;
&lt;table class=&#34;lntable&#34;&gt;&lt;tr&gt;&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code&gt;&lt;span class=&#34;lnt&#34;&gt;1
&lt;/span&gt;&lt;span class=&#34;lnt&#34;&gt;2
&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;
&lt;td class=&#34;lntd&#34;&gt;
&lt;pre tabindex=&#34;0&#34; class=&#34;chroma&#34;&gt;&lt;code class=&#34;language-python&#34; data-lang=&#34;python&#34;&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;k&#34;&gt;with&lt;/span&gt; &lt;span class=&#34;nb&#34;&gt;open&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;(&lt;/span&gt;&lt;span class=&#34;s1&#34;&gt;&amp;#39;file.txt&amp;#39;&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;,&lt;/span&gt; &lt;span class=&#34;n&#34;&gt;encoding&lt;/span&gt;&lt;span class=&#34;o&#34;&gt;=&lt;/span&gt;&lt;span class=&#34;s1&#34;&gt;&amp;#39;utf-8&amp;#39;&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;)&lt;/span&gt; &lt;span class=&#34;k&#34;&gt;as&lt;/span&gt; &lt;span class=&#34;n&#34;&gt;f&lt;/span&gt;&lt;span class=&#34;p&#34;&gt;:&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;span class=&#34;line&#34;&gt;&lt;span class=&#34;cl&#34;&gt;&lt;span class=&#34;c1&#34;&gt;# 处理文件内容&lt;/span&gt;
&lt;/span&gt;&lt;/span&gt;&lt;/code&gt;&lt;/pre&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/div&gt;
&lt;/div&gt;&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;数据问题2：TypeError: cannot unpack non-iterable NoneType object&lt;/b&gt;&lt;br&gt;
已解决：&lt;br&gt;
数据中存在空行和空格，或者存在字段缺失的情况，需要编写python脚本查看是否存在空行空格和字段缺失的情况，如果存在就去掉。&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;关于导入的问题：出现“non-default parameter follows default parameter”这样的错误&lt;/b&gt;&lt;br&gt;
已解决：需要在实例化时保证参数的顺序正确&lt;br&gt;
在函数或类的构造函数中，没有默认值的参数（non-default parameter）跟在了有默认值的参数（default parameter）之后。在Python的函数定义中，所有带有默认值的参数必须位于没有默认值的参数之后。&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;查看CUDA情况：nvidia-smi&lt;/b&gt;&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;p&gt;&lt;b&gt;出现IndexError：&lt;/b&gt;&lt;br&gt;
写一个异常处理，因为是索引错误，一般是数据集的问题，没有处理好，或者数据某一条出现超过最大索引的情况&lt;/p&gt;
&lt;/li&gt;
&lt;/ol&gt;
&lt;p&gt;（——待更新——）&lt;/p&gt;
</description>
        </item>
        <item>
        <title>代码阅读《Text-to-Table: A New Way of Information Extraction</title>
        <link>https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/</link>
        <pubDate>Sun, 16 Apr 2023 20:37:46 +0800</pubDate>
        
        <guid>https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/</guid>
        <description>&lt;img src="https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/VCG211375786999.jpg" alt="Featured image of post 代码阅读《Text-to-Table: A New Way of Information Extraction" /&gt;&lt;p&gt;&lt;img src=&#34;https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/24.jpg&#34;
	width=&#34;1317&#34;
	height=&#34;854&#34;
	srcset=&#34;https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/24_hu8883742009380889468.jpg 480w, https://example.com/p/%E4%BB%A3%E7%A0%81%E9%98%85%E8%AF%BBtext-to-table-a-new-way-of-information-extraction/24_hu8830115649994794633.jpg 1024w&#34;
	loading=&#34;lazy&#34;
	
	
		class=&#34;gallery-image&#34; 
		data-flex-grow=&#34;154&#34;
		data-flex-basis=&#34;370px&#34;
	
&gt;&lt;/p&gt;
</description>
        </item>
        
    </channel>
</rss>
